### ISSUE TITLE
terms.tbx 有 81.3MB 實在是太大了

### ISSUE THREAD

**Issue by doggy8088** [poychang/Lookup-Microsoft-Terms#2]
副檔名 .tbx 在 GitHub Pages 不會自動壓縮，建議更名為 .xml

另一個建議是改用 Cloudflare 當 CDN

**Comment by poychang** [comment]
移除了檔案中用不到的 `termNote` 並更名為 .xml
效果超棒！只需要 4.1 MB 🎉

![image](https://github.com/user-attachments/assets/c7e03078-63b7-4b63-9a8f-ad7cb4e82b16)
